[phases.setup]
nixPkgs = ['php83', 'php83Extensions.mysqli', 'php83Extensions.mbstring']

[phases.install]
cmds = ['composer install --ignore-platform-reqs --no-dev --optimize-autoloader']

[phases.start]
cmd = "bash start.sh"
