[build]

[deploy]
startCommand = "php -S 0.0.0.0:${PORT:-8080}"
healthcheckPath = "/api/auth.php?action=check_auth"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
